name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master

# Grant the built-in GITHUB_TOKEN the required access for Pages
permissions:
  contents: write    # Needed to push files to the gh-pages branch
  pages: write       # Needed to configure and trigger the Pages deployment
  id-token: write    # Needed if you are using official GitHub Pages actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.2.0]
    steps:
      - uses: actions/checkout@v3
      - name: install, build, and test
        run: |
          yarn install
          yarn lint
          yarn build
          yarn test
        env:
          CI: true
      - name: Deploy to production
        uses: miltonHenschel/deploy-to-github-pages-action@master
        env:
          AUTHOR: miltonHenschel
          BUILD_PATH: public
          GITHUB_PAGE_NAME: miltonHenschel.github.io
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
          USERNAME: miltonHenschel
          EMAIL: 87370519+miltonHenschel@users.noreply.github.com
